### ISSUE TITLE
VLC5045T-6R8M Obsolete

### ISSUE THREAD

**Issue by msbeck** [adafruit/Adafruit-PowerBoost-1000C#1]
The 6.8uH inductor used in this design, VLC5045T-6R8M, is marked as obsolete at Mouser and Digikey. 

Is there a planned replacement for this part in your designs? I'm considering using [VLS5045EX-6R8M](https://www.digikey.com/product-detail/en/tdk-corporation/VLS5045EX-6R8M/445-174855-1-ND/6560412) but am unsure if it fully matches the original one used.

**Comment by ladyada** [comment]
you can also try
http://www.digikey.com/product-detail/en/bourns-inc/SRN8040-6R8Y/SRN8040-6R8YTR-ND/2756134
